"""Generate Markdown Report"""

import datetime
from enum import IntEnum
from pathlib import Path

from aiofiles import open as aioopen

from app.config import settings


class ValidationStatus(IntEnum):
    """Status of a given source code"""

    COMPILATION_FAILED = 0
    RUN_FAILED = 1
    INVALID_OUTPUT = 2
    SUCCEEDED = 3


type StudentId = str
type ReportItem = tuple[StudentId, ValidationStatus]


# FIXME not working as expected, write unit test first!
def _unordered_partition_array[T](l: list[T], n: int) -> list[list[T]]:
    """Divide Array Into Sub Array By A Size"""
    return [l[i::n] for i in range(n)]


def _generate_section(title: str, id_list: list[StudentId]) -> str:
    return f"""## {title}

{"\n".join([", ".join(row) for row in _unordered_partition_array(id_list, 9)])}
"""


def _generate_note() -> str:
    return """## Notes

This document generated by validate-assignments.

See: github.com/mahdi-farnia/validate-assignments
"""


class ReportWriter:
    _report_record: list[ReportItem]

    def __init__(self, report_record: list[ReportItem]) -> None:
        self._report_record = report_record

    async def markdown(self):
        async with aioopen(Path(settings.assets_dir) / settings.report_md, "w") as f:
            await f.write(self._gen_report_md(self._report_record))

    def _gen_report_md(self, report: list[ReportItem]) -> str:
        run_failed_runs: list[StudentId] = [
            record[0] for record in report if record[1] == ValidationStatus.RUN_FAILED
        ]
        compilation_failed_runs: list[StudentId] = [
            record[0]
            for record in report
            if record[1] == ValidationStatus.COMPILATION_FAILED
        ]
        invalid_output_runs: list[StudentId] = [
            record[0]
            for record in report
            if record[1] == ValidationStatus.INVALID_OUTPUT
        ]
        successful_runs: list[StudentId] = [
            record[0] for record in report if record[1] == ValidationStatus.SUCCEEDED
        ]

        output: str = f"""# Result For Run {datetime.datetime.now(datetime.timezone.utc)}

    Summary:
    - Total Runs => {len(report)}
    - Successful Runs => {len(successful_runs)}
    - Failed Runs => {len(compilation_failed_runs) + len(run_failed_runs)}
        + Compilation Failed Runs => {len(compilation_failed_runs)}
        + Run Failed Runs => {len(run_failed_runs)}
        + Invalid Output Runs => {len(invalid_output_runs)}

    {_generate_section("Successful Runs", successful_runs)}
    {_generate_section("Compilation Failed Runs", compilation_failed_runs)}
    {_generate_section("Run Failed Runs", run_failed_runs)}
    {_generate_section("Invalid Output Runs", invalid_output_runs)}
    {_generate_note()}"""

        return output
